use_frameworks!

platform :ios, '8.0'

target 'GXNetworking_Example' do
  pod 'GXNetworking', :path => '../'

  target 'GXNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
